List<String> teamNames = [];

List<String> teamsFamous = [
  "CDUB Esports",
  "Fart Studios",
  "nouns",
  "Sand King Gómez",
  "Shopify Rebellion",
  "beastcoast",
  "BOOM Esports",
  "Estar Backs!",
  "HEROIC",
  "Infinity",
  "Lava Esports",
  "Midas Club",
  "Pacific Esports",
  "Qhali",
  "x5 Gaming",
  "B8",
  "Entity",
  "Gaimin Gladiators",
  "MOUZ",
  "Rest Farmers",
  "Team Liquid",
  "Team Secret",
  "Tundra Esports",
  "1win",
  "9Pandas",
  "BetBoom Team",
  "L1GA TEAM",
  "Marlerino eSports ",
  "Natus Vincere",
  "NAVI Junior",
  "Nemiga Gaming",
  "SIBE team",
  "Team Spirit",
  "Virtus.pro",
  "Azure Ray",
  "G2 x iG",
  "Invictus Gaming",
  "LGD Gaming",
  "Team Bright",
  "Team Zero",
  "Xtreme Gaming",
  "Aurora",
  "Blacklist Rivalry ",
  "Bleed Esports",
  "Execration",
  "Geek Fam",
  "IHC",
  "Myth Avenue Gaming",
  "Neon Esports",
  "Talon",
  "Yangon Galacticos",
  "Nigma Galaxy",
  "PSG LGD",
  "Team Falcons",
  "Winter Bear",
];